// react-example/src/App.tsx
import {DBCustomSelect} from "@db-ux/react-core-components";

const App = () => {
  return (
    <main>
        <DBCustomSelect
            options={[{ value: "Option 1" }, { value: "Option 2" }]}
            placeholder="Placeholder"
            label="Label"
            multiple
            onSelect={values => console.log(values)}
        >

        </DBCustomSelect>
    </main>
  );
};

export default App;

// vue-example/src/App.vue
<script setup lang="ts">
import {DBCustomSelect} from "@db-ux/v-core-components";
import {ref} from "vue";

const options = ref([{"value":"Option 1"},{"value":"Option 2"}])

</script>

<template>
  <main>
    <DBCustomSelect :options="options" multiple placeholder="Placeholder" label="Label" :on-select="values=>console.log(values)">
    </DBCustomSelect>
  </main>
</template>
