// react-example/src/App.tsx
import {DBCustomSelect} from "@db-ux/react-core-components";

const App = () => {
  return (
    <main>
        <DBCustomSelect
            options={[{ value: "Option 1" }, { value: "Option 2" }]}
            placeholder="Placeholder"
            label="Label"
            multiple
            onSelect={values => console.log(values)}
        >

        </DBCustomSelect>
    </main>
  );
};

export default App;

// angular17-example/src/app/app.component.ts
import {Component, CUSTOM_ELEMENTS_SCHEMA} from '@angular/core';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class AppComponent {
  protected readonly console = console;

  options = [{ value: 'Option 1' }, { value: 'Option 2' }];
}

<db-custom-select
  [options]="options"
  placeholder="Placeholder"
  label="bla"
  [multiple]="true"
  (onSelect)="console.log($event)"
>
</db-custom-select>
